author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /test-with-neg-y
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    deep_zoom: true
    extra_js:
    - volume-page.js
    - hammer.min.js
    - deepzoom.js
    - openseadragon.min.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: https://images.readux.ecds.emory.edu:8443/cantaloupe/iiif/2/23628489-f27b-4e4d-a76f-8d81a313effe_MSS0921-B030-F009-I001-P001-PROD.jpg/full/full/0/default.jpg
image_size:
  page:
    height: 8800
    width: 3670
permalink: pretty
publication_info:
  date: '2021'
  editors: []
  title: Les Jubilee Singers
show_annotation_author: true
source_info:
  title: Les Jubilee Singers
  via_readux: true
tagline: an annotated digital edition
title: Les Jubilee Singers
url: https://jayvarner.github.io
version: 0.7
